#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

echo "[1/8] JS syntax check"
find src games -name '*.js' -print0 | xargs -0 -n1 node --check >/dev/null

echo "[2/8] Game modules existence"
required=(
  "games/meteor-dodge/index.html"
  "games/meteor-dodge/main.js"
  "games/meteor-dodge/state.js"
  "games/meteor-dodge/input.js"
  "games/meteor-dodge/renderer.js"
  "games/meteor-dodge/systems.js"
  "games/meteor-dodge/difficulty.js"
  "games/meteor-dodge/sfx.js"
  "games/meteor-dodge/ui.js"
  "games/shared/ui.common.js"
  "games/shared/confetti.fx.js"
  "games/shared/sfx.runtime.js"
  "games/shared/vendor/confetti.browser.min.js"
  "scripts/shared-ui-common-check.mjs"
  "scripts/game-ui-check.mjs"
  "scripts/mission-index-sync-check.mjs"
  "scripts/longpress-guard-check.mjs"
  "games/meteor-dodge/assets/sfx/item.wav"
  "games/meteor-dodge/tests/QA_CHECKLIST.md"
  "games/lane-switch/tests/QA_CHECKLIST.md"
  "QA_MOBILE_2DEVICES.md"
  "QA_FINAL_STATUS.md"
  "QA_3RUN_LOG_TEMPLATE.md"
  "assets/previews/meteor-dodge-preview.png"
  "assets/previews/meteor-dodge-shot-1.png"
  "games/lane-switch/index.html"
  "games/lane-switch/main.js"
  "games/lane-switch/ui.js"
  "games/lane-switch/state.js"
  "games/lane-switch/input.js"
  "games/lane-switch/renderer.js"
  "games/lane-switch/systems.js"
  "games/lane-switch/sfx.js"
  "games/sky-drift/index.html"
  "games/sky-drift/main.js"
  "games/sky-drift/state.js"
  "games/sky-drift/input.js"
  "games/sky-drift/renderer.js"
  "games/sky-drift/systems.js"
  "games/sky-drift/sfx.js"
  "games/sky-drift/ui.js"
  "games/sky-drift/tests/QA_CHECKLIST.md"
  "games/neon-brick-breaker/index.html"
  "games/neon-brick-breaker/main.js"
  "games/neon-brick-breaker/state.js"
  "games/neon-brick-breaker/input.js"
  "games/neon-brick-breaker/renderer.js"
  "games/neon-brick-breaker/systems.js"
  "games/neon-brick-breaker/sfx.js"
  "games/neon-brick-breaker/ui.js"
  "games/neon-brick-breaker/tests/QA_CHECKLIST.md"
  "games/orbit-survivor/index.html"
  "games/orbit-survivor/main.js"
  "games/orbit-survivor/state.js"
  "games/orbit-survivor/input.js"
  "games/orbit-survivor/renderer.js"
  "games/orbit-survivor/systems.js"
  "games/orbit-survivor/sfx.js"
  "games/orbit-survivor/ui.js"
  "games/orbit-survivor/tests/QA_CHECKLIST.md"
  "games/block-sage/index.html"
  "games/block-sage/main.js"
  "games/block-sage/state.js"
  "games/block-sage/input.js"
  "games/block-sage/renderer.js"
  "games/block-sage/systems.js"
  "games/block-sage/sfx.js"
  "games/block-sage/ui.js"
  "games/block-sage/tests/QA_CHECKLIST.md"
  "games/mini-empire/index.html"
  "games/mini-empire/main.js"
  "games/mini-empire/state.js"
  "games/mini-empire/input.js"
  "games/mini-empire/renderer.js"
  "games/mini-empire/systems.js"
  "games/mini-empire/sfx.js"
  "games/mini-empire/ui.js"
  "games/mini-empire/tests/QA_CHECKLIST.md"
  "games/pixel-clash/index.html"
  "games/pixel-clash/main.js"
  "games/pixel-clash/state.js"
  "games/pixel-clash/input.js"
  "games/pixel-clash/renderer.js"
  "games/pixel-clash/systems.js"
  "games/pixel-clash/sfx.js"
  "games/pixel-clash/ui.js"
  "games/pixel-clash/tests/QA_CHECKLIST.md"
  "games/idle-foundry/index.html"
  "games/idle-foundry/main.js"
  "games/idle-foundry/state.js"
  "games/idle-foundry/input.js"
  "games/idle-foundry/renderer.js"
  "games/idle-foundry/systems.js"
  "games/idle-foundry/sfx.js"
  "games/idle-foundry/ui.js"
  "games/idle-foundry/tests/QA_CHECKLIST.md"
  "games/dash-to-core/index.html"
  "games/dash-to-core/main.js"
  "games/dash-to-core/state.js"
  "games/dash-to-core/input.js"
  "games/dash-to-core/renderer.js"
  "games/dash-to-core/systems.js"
  "games/dash-to-core/sfx.js"
  "games/dash-to-core/ui.js"
  "games/dash-to-core/tests/QA_CHECKLIST.md"
  "games/farm-harbor/index.html"
  "games/farm-harbor/main.js"
  "games/farm-harbor/state.js"
  "games/farm-harbor/input.js"
  "games/farm-harbor/renderer.js"
  "games/farm-harbor/systems.js"
  "games/farm-harbor/sfx.js"
  "games/farm-harbor/ui.js"
  "games/farm-harbor/tests/QA_CHECKLIST.md"
  "games/mecha-sprint/index.html"
  "games/mecha-sprint/main.js"
  "games/mecha-sprint/state.js"
  "games/mecha-sprint/input.js"
  "games/mecha-sprint/renderer.js"
  "games/mecha-sprint/systems.js"
  "games/mecha-sprint/sfx.js"
  "games/mecha-sprint/ui.js"
  "games/mecha-sprint/tests/QA_CHECKLIST.md"
  "games/maze-signal/index.html"
  "games/maze-signal/main.js"
  "games/maze-signal/state.js"
  "games/maze-signal/input.js"
  "games/maze-signal/renderer.js"
  "games/maze-signal/systems.js"
  "games/maze-signal/sfx.js"
  "games/maze-signal/ui.js"
  "games/maze-signal/tests/QA_CHECKLIST.md"
  "games/void-raiders/index.html"
  "games/void-raiders/main.js"
  "games/void-raiders/state.js"
  "games/void-raiders/input.js"
  "games/void-raiders/renderer.js"
  "games/void-raiders/systems.js"
  "games/void-raiders/sfx.js"
  "games/void-raiders/ui.js"
  "games/void-raiders/tests/QA_CHECKLIST.md"
  "games/rail-commander/index.html"
  "games/rail-commander/main.js"
  "games/rail-commander/state.js"
  "games/rail-commander/input.js"
  "games/rail-commander/renderer.js"
  "games/rail-commander/systems.js"
  "games/rail-commander/sfx.js"
  "games/rail-commander/ui.js"
  "games/rail-commander/tests/QA_CHECKLIST.md"
  "assets/previews/block-sage-preview.png"
  "assets/previews/mini-empire-preview.png"
  "assets/previews/pixel-clash-preview.png"
  "assets/previews/idle-foundry-preview.png"
  "assets/previews/dash-to-core-preview.png"
  "assets/previews/farm-harbor-preview.png"
  "assets/previews/mecha-sprint-preview.png"
  "assets/previews/maze-signal-preview.png"
  "assets/previews/void-raiders-preview.png"
  "assets/previews/rail-commander-preview.png"
  "assets/previews/lane-switch-preview.png"
  "assets/previews/lane-switch-shot-1.png"
  "assets/previews/sky-drift-preview.png"
  "assets/previews/sky-drift-shot-1.svg"
  "assets/previews/neon-brick-breaker-preview.svg"
  "assets/previews/neon-brick-breaker-shot-1.svg"
  "assets/previews/orbit-survivor-preview.svg"
  "assets/previews/orbit-survivor-shot-1.svg"
)
for f in "${required[@]}"; do
  [[ -f "$f" ]] || { echo "Missing: $f"; exit 1; }
done

echo "[3/8] HTTP smoke check"
python3 -m http.server 8790 >/tmp/meteor_smoke_http.log 2>&1 &
SERVER_PID=$!
trap 'kill $SERVER_PID >/dev/null 2>&1 || true' EXIT
sleep 1
for p in / /admin.html /games/meteor-dodge/index.html /games/meteor-dodge/main.js /games/meteor-dodge/state.js /games/meteor-dodge/input.js /games/meteor-dodge/renderer.js /games/meteor-dodge/systems.js /games/meteor-dodge/difficulty.js /games/meteor-dodge/sfx.js /games/meteor-dodge/ui.js /games/shared/ui.common.js /games/shared/confetti.fx.js /games/shared/sfx.runtime.js /games/shared/vendor/confetti.browser.min.js /games/meteor-dodge/assets/sfx/item.wav /games/lane-switch/index.html /games/lane-switch/main.js /games/lane-switch/ui.js /games/lane-switch/state.js /games/lane-switch/input.js /games/lane-switch/renderer.js /games/lane-switch/systems.js /games/lane-switch/sfx.js /games/sky-drift/index.html /games/sky-drift/main.js /games/sky-drift/state.js /games/sky-drift/input.js /games/sky-drift/renderer.js /games/sky-drift/systems.js /games/sky-drift/sfx.js /games/sky-drift/ui.js /games/neon-brick-breaker/index.html /games/neon-brick-breaker/main.js /games/neon-brick-breaker/state.js /games/neon-brick-breaker/input.js /games/neon-brick-breaker/renderer.js /games/neon-brick-breaker/systems.js /games/neon-brick-breaker/sfx.js /games/neon-brick-breaker/ui.js /games/orbit-survivor/index.html /games/orbit-survivor/main.js /games/orbit-survivor/state.js /games/orbit-survivor/input.js /games/orbit-survivor/renderer.js /games/orbit-survivor/systems.js /games/orbit-survivor/sfx.js /games/orbit-survivor/ui.js /games/block-sage/index.html /games/block-sage/main.js /games/block-sage/state.js /games/block-sage/input.js /games/block-sage/renderer.js /games/block-sage/systems.js /games/block-sage/sfx.js /games/block-sage/ui.js /games/mini-empire/index.html /games/mini-empire/main.js /games/mini-empire/state.js /games/mini-empire/input.js /games/mini-empire/renderer.js /games/mini-empire/systems.js /games/mini-empire/sfx.js /games/mini-empire/ui.js /games/pixel-clash/index.html /games/pixel-clash/main.js /games/pixel-clash/state.js /games/pixel-clash/input.js /games/pixel-clash/renderer.js /games/pixel-clash/systems.js /games/pixel-clash/sfx.js /games/pixel-clash/ui.js /games/idle-foundry/index.html /games/idle-foundry/main.js /games/idle-foundry/state.js /games/idle-foundry/input.js /games/idle-foundry/renderer.js /games/idle-foundry/systems.js /games/idle-foundry/sfx.js /games/idle-foundry/ui.js /games/dash-to-core/index.html /games/dash-to-core/main.js /games/dash-to-core/state.js /games/dash-to-core/input.js /games/dash-to-core/renderer.js /games/dash-to-core/systems.js /games/dash-to-core/sfx.js /games/dash-to-core/ui.js /games/farm-harbor/index.html /games/farm-harbor/main.js /games/farm-harbor/state.js /games/farm-harbor/input.js /games/farm-harbor/renderer.js /games/farm-harbor/systems.js /games/farm-harbor/sfx.js /games/farm-harbor/ui.js /games/mecha-sprint/index.html /games/mecha-sprint/main.js /games/mecha-sprint/state.js /games/mecha-sprint/input.js /games/mecha-sprint/renderer.js /games/mecha-sprint/systems.js /games/mecha-sprint/sfx.js /games/mecha-sprint/ui.js /games/maze-signal/index.html /games/maze-signal/main.js /games/maze-signal/state.js /games/maze-signal/input.js /games/maze-signal/renderer.js /games/maze-signal/systems.js /games/maze-signal/sfx.js /games/maze-signal/ui.js /games/void-raiders/index.html /games/void-raiders/main.js /games/void-raiders/state.js /games/void-raiders/input.js /games/void-raiders/renderer.js /games/void-raiders/systems.js /games/void-raiders/sfx.js /games/void-raiders/ui.js /games/rail-commander/index.html /games/rail-commander/main.js /games/rail-commander/state.js /games/rail-commander/input.js /games/rail-commander/renderer.js /games/rail-commander/systems.js /games/rail-commander/sfx.js /games/rail-commander/ui.js /assets/previews/meteor-dodge-preview.png /assets/previews/meteor-dodge-shot-1.png /assets/previews/block-sage-preview.png /assets/previews/mini-empire-preview.png /assets/previews/pixel-clash-preview.png /assets/previews/idle-foundry-preview.png /assets/previews/dash-to-core-preview.png /assets/previews/farm-harbor-preview.png /assets/previews/mecha-sprint-preview.png /assets/previews/maze-signal-preview.png /assets/previews/void-raiders-preview.png /assets/previews/rail-commander-preview.png /assets/previews/lane-switch-preview.png /assets/previews/lane-switch-shot-1.png /assets/previews/sky-drift-preview.png /assets/previews/sky-drift-shot-1.svg /assets/previews/neon-brick-breaker-preview.svg /assets/previews/neon-brick-breaker-shot-1.svg /assets/previews/orbit-survivor-preview.svg /assets/previews/orbit-survivor-shot-1.svg; do
  code=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:8790$p")
  if [[ "$code" != "200" ]]; then
    echo "HTTP check failed: $p => $code"
    exit 1
  fi
done

kill $SERVER_PID >/dev/null 2>&1 || true
trap - EXIT

echo "[4/8] Roadmap file check"
[[ -f ROADMAP_0.3.0.md ]] || { echo "Missing ROADMAP_0.3.0.md"; exit 1; }

echo "[5/8] Shared UI common check"
node scripts/shared-ui-common-check.mjs >/dev/null

echo "[6/8] Mission index sync check"
node scripts/mission-index-sync-check.mjs >/dev/null

echo "[7/8] Longpress guard check"
node scripts/longpress-guard-check.mjs >/dev/null

echo "[8/8] Game UI check"
node scripts/game-ui-check.mjs >/dev/null

echo "Smoke check passed ✅"
